# Generated by Django 5.0.6 on 2024-05-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
