# Generated by Django 4.2.2 on 2024-04-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
        migrations.DeleteModel(
            name='QuestionTrack',
        ),
    ]
