# Generated by Django 4.2.2 on 2024-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tracks_track_delete_questiontrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='options', to='api.option'),
        ),
    ]
