# Generated by Django 4.2.2 on 2024-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_partnerships'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('instragram', models.CharField(max_length=20)),
            ],
        ),
    ]
