# Generated by Django 5.0.6 on 2024-05-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_question_options'),
        ('api', '0008_contactinformation'),
    ]

    operations = [
    ]
