# Generated by Django 5.0.6 on 2024-05-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20240520_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='options', to='api.option'),
        ),
    ]
